name = "AtomsView"
uuid = "ee286e10-dd2d-4ff2-afcb-0a3cd50c8041"
authors = ["Michael F. Herbst <info@michael-herbst.com>"]
version = "0.1.4"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
Bio3DView = "99c8bb3a-9d13-5280-9740-b4880ed9c598"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
AtomsBase = "0.4, 0.5"
Bio3DView = "1"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
